site_name: Machine Learning engineer Training Program
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
theme: readthedocs
repo_url: https://github.com/itandi/mltp
pages:
    - Home: index.md
    - Traditional Machine Learning:
      - Unit1:
        - 'Introduction': 'section1/unit1/introduction.md'
        - 'k-Nearest Neighbors': 'section1/unit1/k-nn.md'
      - Unit2:
        - 'Supervised Learning': 'section1/unit2/supervised_learning.md'
      - Unit3:
        - 'Naive Bayes': 'section1/unit3/naive_bayes.md'
      - Unit4:
        - 'K-Means Clustering': 'section1/unit4/k-means.md'
      - Unit5:
        - 'Linear Regression': 'section1/unit5/linear_regression.md'
      - Unit6:
        - 'Logistic Regression': 'section1/unit6/logistic_regression.md'
    - Deep Learning:
      - Unit7:
        - 'Logistic Regression2': 'section2/unit7/logistic_regression2.md'